### ISSUE TITLE
' issueベースの開発' レビュー依頼

### ISSUE THREAD

**Issue by 1068haruto** [1068haruto/portfolio#48]
■Webアプリの概要
このサービスは、ユーザー自身の経済状況を多面的に把握し、今後の資産形成やキャリア形成の計画をサポートするツールです。
主要な機能は次の2つです。
①経済的シナリオのシミュレーション：ユーザーが現状と理想の状態の入力情報から、「現状の豊かさ」「現実的な将来の経済状態」「理想的な将来とのギャップ」をシミュレーション・グラフ表示し、ユーザーの経済的立ち位置を視覚化します。
②時系列のメモ管理：登録したライフイベントを確認しながら時系列にメモを追加でき、独自の人生ロードマップを管理することが可能です。
20代後半から40代前半のライフイベントが集中する層をターゲットとしており、結婚、住宅購入、子どもの教育等のユーザーのライフプランに応じた支出項目が追加できる点や、理想から見た現状のギャップの可視化を通じて資産やキャリア形成の見直しを促せる点が特徴です。
サービス利用の流れ：【情報入力】→【シミュレーション, 結果確認】→【ライフプラン確認, メモ追加】→【再シミュレーション】

■1週間辺りの開発に向けられる時間
- 1週間あたり：56時間

■ProjectsのURL
https://github.com/users/1068haruto/projects/1

■MVPリリースまで
- [ ] Herokuにデプロイ
- [ ] トップページ
- [ ] ユーザー登録・ログイン機能
- [ ] シミュレーション機能
- [ ] グラフ表示機能
- [ ] メモ機能

■MVP後
- [ ] 利用規約
- [ ] プライバシーポリシー
- [ ] お問い合わせ
- [ ] RSpec
- [ ] レスポンシブ対応

■MVPレビュー依頼予定日
予定日：2024年 12月 6日

**Comment by kashiwagi-rena** [comment]
提出いただきありがとうございます。
以下、コメントです。

---

- MYP後の実装内容も記載してください
- デプロイは新機能追加したタイミングで行うことをおすすめします

**Comment by 1068haruto** [comment]
ありがとうございます。
デプロイタイミング、承知しました。

> * MYP後の実装内容も記載してください
上記につきまして質問です。
学習カリキュラム - issueベースの開発ページ内の指示では、「1週間ごとの列を作成し、MVPリリースまでのスケジュールを作成してください。」とありますが、MVP後のスケジュールもissue作成の必要があるということでしょうか？
